import Head from "next/head";
import BackgroundHome from "../components/backgroundHome/BackgroundHome";
import Header from "../components/header/Header";
import ListBook from "../components/listBook/ListBook";
import Loading from "../components/loading/Loading";
import React, { useEffect } from "react";
import { useDispatch, useSelector } from "react-redux";
import { fetchApiGetAllBooks } from "../redux/apiRequest";

export default function Home() {
  const dispatch = useDispatch();
  const loading = useSelector((state) => state.book.loading);
  const listBook = useSelector((state) => state.book.book);
  // console.log("list", listBook);

  useEffect(() => {
    fetchApiGetAllBooks(dispatch);
  }, []);

  return (
    <>
      {loading && <Loading />}
      <Head>
        <title>Book Store App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <BackgroundHome />
      <ListBook listBook={listBook} />
    </>
  );
}
